# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./guest_room.h \
    ./room_manager.h \
    ./test_621.h
SOURCES += ./guest_room.cpp \
    ./room_manager.cpp \
    ./test_621.cpp \
    ./main.cpp
FORMS += ./test_621.ui
RESOURCES += test_621.qrc
